export enum STATUS {
  TODO = "TO_DO",
  IN_PROGRESS = "IN_PROGRESS",
  DONE = "DONE",
}

export enum MODAL_TYPES {
  ADD_TASK_MODAL = "ADD_TASK_MODAL",
  EDIT_TASK_MODAL = "EDIT_TASK_MODAL",
  DELETE_TASK_MODAL = "DELETE_TASK_MODAL",
}

export enum SORT_TYPES {
  ASC_ALPHA = "ASC_ALPHA",
  DESC_ALPHA = "DESC_ALPHA",
  ASC_DATE = "ASC_DATE",
  DESC_DATE = "DESC_DATE",
  CUSTOM = "CUSTOM"
}